### PR TITLE
made form submit button work

### PR DESCRIPTION
**Pull request by sarah-weatherbee**

### CODE REVIEW

**Comment by mtgill** [comment]
@sarah-weatherbee  It looks like there's a merge conflict of some kind, if you can resolve it I'll go ahead and pull down your code.

**Comment by tilleraj** [comment]
Conflicts resolved

**Comment by mtgill** [comment]
@sarah-weatherbee  Getting an error on line 26
```document.getElementById("booked").addEventListener("click", confirmation);```
Would try putting ^^ in a function that checks if the divId is null or not, and then adding that function to init()

**Comment by mtgill** [comment]
Issue at line 10 and line 32, both eventListener issues

**Comment by mtgill** [comment]
@sarah-weatherbee possible fix for issue at line 32 below

```
const tourButtonEvents = () => {
   if (document.getElementById("book-tour-button") !== null){
    document.getElementById("book-tour-button").addEventListener("click", tourForm);
    }
};
```

**Comment by mtgill** [comment]
👍  all set!

**Pull request merged**
