### PR TITLE
Mg home

### LINKED ISSUE #8: Page: Home
## User Story
As a user, when I look at the homepage, I should see a beautiful picture of beer, a paragraph & photo telling the story of the brewery, and a paragraph and photo introducing me to the facility.

## AC
**WHEN** I look at the homepage
**THEN** I should see a Bootstrap Jumbotron with an image of beer
**AND** A paragraph describing "our story" paired with the image of our Fearless Leader™ Barbarian Streisand and a link to nav to the Beers we Brew page
**AND** A paragraph about our facility paired with an image of a nuclear power-plant and a link to the Book a Tour page

## Development
* if it doesn't exist already, create a home.html file
* add a jumbotron with the following CSS:
```css
.jumbotron {
  background-image: url("totallyAwesome.jpg");
  background-size: cover;
}
```
* add a div for "Our Story"
  - col-7 for the `<p>` with the copy and the link
  - col-5 for the image and caption
* Add a div for "Our Facility"
  - col-7 for the `<p>` with the copy and the link
  - col-5 for the image and caption

### PR DESCRIPTION
**Pull request by mtgill**
closes #8

### CODE REVIEW

**Comment by mtgill** [comment]
@tilleraj

**Comment by tilleraj** [comment]
Looks like the Jumbotron is containing the whole page instead of just the image at the top.
Mockup/dev notes may have been unclear, but the two divs should be below the jumbo, not part of it

**Comment by mtgill** [comment]
@tilleraj comments above have been resolved

**Comment by tilleraj** [comment]
👍 fixes implemented successfully

**Pull request merged**
